
if not LOCALE_frFR then return; end

local L = LibStub("LibTime-1.0").countryLocalizedNames;

L["Allows you to adjust the display options."] = "Vous permet de modifier les options."
L["Bags"] = "Sacs"
L["Broker_Everything will use the new setting on next reload."] = "Broker_Everything prendra en compte la nouvelle configuration au prochain chargement."
L["Calendar"] = "Calendrier"
L["Cfg"] = "Cfg"
L["CmdUsage"] = "/be ou /broker_everything pour afficher les commandes par le chat"
L["Collecting Garbage..."] = "Mise en mémoire..."
L["Coordinates"] = "Coordonnées"
L["Disabling %s on next reload."] = "Désactivation %s au prochain chargement."
L["Enable to play a sound on receiving a new mail message. Default is off"] = "Active un son à la réception d'un courrier. Désactivé par défaut."
L["Enable/disable tooltip scaling."] = "Active/Désactive le redimensionnement des tooltips"
L["Enabling %s on next reload."] = "Activation %s au prochain chargement."
L["Friends"] = "Amis"
L["GPS"] = "GPS"
L["Hidden"] = "Caché"
L["Home"] = "Personnel"
L["Latency"] = "Latence"
L["Location"] = "Localisation"
L["Memory"] = "Mémoire"
L["ModDesc-FPS"] = "Affiche votre fps."
L["ModDesc-Friends"] = "Affiche vos amis en ligne."
L["ModDesc-Gold"] = "Vous donne des informations sur votre or. Rerolls, gains, pertes durant la session."
L["ModDesc-GPS"] = "Affiche le nom de la zone actuelle et les coordonnées."
L["ModDesc-Location"] = "Affiche vos coordonnées actuelles."
L["ModDesc-Stuff"] = "Vous permet de passer en mode fenêtré, recharger l'UI, se déconnecter et quitter."
L["ModDesc-XP"] = "Affiche votre xp en pourcentage ou en valeur absolue."
L["ModDesc-ZoneText"] = "Affiche le nom de la zone actuelle."
L["Nameplates"] = "Affichage des noms"
L["No guild"] = "Sans Guilde"
L["No Mail"] = "Pas de Courrier"
L["Notes"] = "Notes"
L["Options"] = "Options"
L["OptReloadUI"] = "Recharger l'UI"
L["OptTTScale"] = "dimensionnement de la tooltip"
L["Play sound on new mail"] = "Jouer un son à la réception d'un courrier"
L["Real ID"] = "ID Réelle"
L["Realm"] = "Royaume"
L["Reputation discounts"] = "Réputations"
L["Rest"] = "Repos"
L["Select to show XP as an absolute value; Deselected will show it as a percentage."] = "Activer pour afficher l'XP en valeur absolue. Désactiver pour l'afficher en pourcentage."
L["Showing a maximum of %d addons."] = "Affiche un maximum de %d d'addons."
L["Showing all addons."] = "Affiche tous les addons."
L["Shown"] = "Montrer"
L["Stuff"] = "Equippement"
L["TimeRealm"] = "Heure Serveur"
L["Total Gold"] = "Total Or"
L["World"] = "Monde"
L["ZoneText"] = "Zone de Texte"

